### ISSUE TITLE
Introduce SSL

### ISSUE THREAD

**Issue by mame82** [mame82/P4wnP1_go#30]
The implementation **is not hardened against attacks**.
SSL with a self signed cert should be introduced to for the web service.

- [ ] provide self signed cert when necessary
- [ ] allow wrapping WebSockets for gRPC-web into SSL
- [ ] wrap static HTTP content into SSL

**Comment by mame82** [comment]
Won't be implemented

**Comment by nomorehey** [comment]
Why not use ssh tunneling to localhost?
